### ISSUE TITLE
Password length limitation is incorect

### ISSUE THREAD

**Issue by artonge** [cozy/cozy-konnector-malakoffmederic#7]
Hi,

The password length seems to be incorrect. It's fixed at 15 characters but it can actually be longer (mine is 128).

I couldn't find where to change that. Could you either tell me where to look or fix it ?

Thanks for the konnector by the way !

**Comment by artonge** [comment]
Fixed: https://github.com/cozy/cozy-collect/pull/491

**Comment by ptbrowne** [comment]
Thanks !
